# This file is a template, and might need editing before it works on your project.
image: docker:19.03

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03-dind

before_script:
    - docker info


build:
    script:
      - ip addr
      - docker pull 172.17.0.1:2375/kalka/steamcmd
